spring.application.name=sistema-de-matriculas

# URL de conexão: altera "sistema_matriculas" para o nome do banco que você criou no Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_matriculas

# Usuário e Senha do seu PostgreSQL (coloque os que você configurou quando instalou o Postgres)
spring.datasource.username=postgres
spring.datasource.password=admin

# Driver do banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# O 'update' faz o Spring criar as tabelas automaticamente no Postgres para você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect